apiVersion: v1
kind: Namespace
metadata: 
  name: development
---  
apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-mem-limit-range
  namespace: development
spec:
  limits:
    - default:
        cpu: "500m" 
        memory: "512Mi"
      defaultRequest:
        cpu: "300m"
        memory: "256Mi"
      type: Container 
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: development
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi  
    pods: "5"    
    configmaps: "5" 
    persistentvolumeclaims: "5" 
    secrets: "5" 
    services: "5"
