apiVersion: v1
kind: Service
metadata:
  name: rails-crud-service
  labels: 
    app: rails-crud
spec:
  type: NodePort
  selector:
    app: rails-crud
  ports: 
    - port: 3000
      targetPort: 3000
      nodePort: 31231