apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-postgres-pv-claim
  namespace: dev3
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources: 
    requests:
      storage: 4Gi